name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: "3.10"
    - name: Install lint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
        pdm add black
        pdm add flake8
        pdm add mypy
    - name: Analysing the code
      run: |
        pdm run python -m black src/* --check
        pdm run python -m black tests/* --check
        pdm run python -m flake8 src/* --max-line-length=80 --extend-select=B950 --extend-ignore=E203,E501,E701
        pdm run python -m mypy .
