name: sphinx

on: [push, pull_request]

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: "3.10"
    - name: Install sphinx dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
    - name: Publishing the documentation using sphinx
      run: |
        cd docs/
        pdm run make clean
        pdm run make html
