name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install pytest dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
        pdm add pytest
    - name: Testing the code with Pytest
      run: pdm run python -m pytest
