name: test

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: "3.10"
    - name: Install pytest dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        pdm install
        pdm add pytest
    - name: Testing the code with Pytest
      continue-on-error: true
      run: pdm run python -m pytest
